### ISSUE TITLE
Commands not working in Tutor Interactive Shell in web plugin

### ISSUE THREAD

**Issue by Abdul-Muqadim-Arbisoft** [overhangio/tutor-webui#14]
**issue description**
When attempting to use the help command within the Tutor interactive shell, the system returns an error message indicating that there is no such command as 'help'. Additionally, attempting to use a command like 'local launch' results in a similar error, followed by an unhandled exception in the event loop related to the Click context management.

**Steps to Reproduce:**
Enter the Tutor interactive shell.
Type help and press Enter.
Observe the error message: Error: No such command 'help'.
Type local launch or any existent command and press Enter.
Notice the  exception related to Click's command resolution.

**Expected Behavior:**
The Tutor interactive shell should provide a list of available commands when the help command is entered.Or any existent commands like local launch, to run tutor should work 
**Actual Behavior:**
The help command is not recognized, and an error message is displayed.
Entering existent commands leads to exceptions

**Comment by hinakhadim** [comment]
Created PR #13
